# Generated by Django 5.1.2 on 2024-12-12 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_firstappuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('action', models.CharField(choices=[('login', 'login succ'), ('question', 'look question list'), ('vote', 'Vote a question'), ('detail', 'view singe question info')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.firstappuser')),
            ],
        ),
    ]
